[project]
name = "vvis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.1",
    "pyqt6>=6.11.0",
    "pyserial>=3.5",
    "pyvista>=0.48.4",
]

[dependency-groups]
dev = [
    "basedpyright>=1.39.9",
    "ruff>=0.16.0",
]
